# Generated by Django 2.0.2 on 2020-08-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0003_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area_code',
            field=models.CharField(max_length=10, null=True, verbose_name='区域代号'),
        ),
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=100, null=True, verbose_name='区县'),
        ),
        migrations.AddField(
            model_name='address',
            name='realname',
            field=models.CharField(max_length=100, null=True, verbose_name='真是姓名'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='address',
            name='detail_road',
            field=models.CharField(max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否是默认地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=100, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
